// client/src/components/DiscardPile.tsx
import React from "react";
import UnoCard from "./Card";
import './styles/DiscardPile.css';

const DiscardPile: React.FC = () => {

  const topCard = discardPileStore.topCard;

  return (
    <div>
      {topCard ? (
        <UnoCard card={topCard} />
      ) : (
        <div className="empty-space"></div>
      )}
    </div>
  );
};

export default DiscardPile;

// client/src/components/DiscardPile.vue
<script setup lang="ts">
import { useDiscardPileStore } from '@/stores/DiscardPileStore';
import UnoCard from './Card.vue';

const discardPileStore = useDiscardPileStore();

</script>

<template>
  <div>
    <div v-if="discardPileStore.topCard">
      <UnoCard :card="discardPileStore.topCard" />
    </div>
    <div v-else >
      <div class= "empty-space"></div>
    </div>
  </div>
</template>

<style>
.empty-space {
  height: 14rem;
  width: 9.4rem
}
</style>
