// client/src/components/OpponentHand.vue
<script setup lang="ts">
import type { PlayerHand } from "domain/src/model/playerHand";
import opponentImg from "@/components/images/opponentCards.png"

defineProps<{
  opponent: PlayerHand;
}>();
</script>

<template>
  <div class="opponent-container">
    <div class="opponent-name">
      {{ opponent.playerName }}
    </div>

    <img
      :src="opponentImg"
      alt="Opponent's cards"
      class="opponent-card"
    />
  </div>
</template>

<style scoped>
.opponent-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 0.5rem;
}

.opponent-name {
  font-family: 'Trebuchet MS', sans-serif;
  font-size: 1rem;
  font-weight: 700;
  margin-bottom: 0.25rem;
  color: white;
}

.opponent-card {
  height: 10rem; 
  object-fit: contain;
}
</style>

// client/src/components/OpponentHand.tsx
import React from "react";
import type { PlayerHand } from "domain/src/model/playerHand";
import opponentImg from "@/components/images/opponentCards.png";
import './styles/OpponentHand.css';

interface OpponentHandProps {
  opponent: PlayerHand;
  className?: string;
}

const OpponentHand: React.FC<OpponentHandProps> = ({ opponent, className }) => {
  return (
    <div className={`opponent-container ${className || ""}`}>
      <div className="opponent-name">{opponent.playerName}</div>
      <img src={opponentImg} alt="Opponent's cards" className="opponent-card" />
    </div>
  );
};

export default OpponentHand;
